#!/usr/bin/env ruby

require 'optparse'

require 'bacula/console'

class BaculaRestore < OptionParser
  def initialize
    super nil, 16, ''

    self.banner = \
      "Usage: #{program_name} [options] --all | <job>...\n" +
      "       #{program_name} [options] --list-jobs"

    on '--all',
      'Run all applicable restore jobs' do
      @all = true
    end

    on '--force',
      'Continue even on job failures' do
      @force = true
    end

    on '--list-jobs',
      'List backup jobs applicable for restoring on this client' do
      @action = :list_jobs
    end

    on '--restoreclient=CLIENT',
      'Restore to a different client instead of the local host' do |client|
      @restoreclient = ensure_client client
    end

    @all = false
    @force = false
    @action = nil
    @restoreclient = nil

    @client = `hostname`.chomp.sub(/\..*/, '')
  end

  def restoreclient
    @restoreclient || @client
  end

  def bconsole
    @bconsole ||= Bacula::Console.new
  end

  def clients
    @clients ||= bconsole.clients
  end

  def ensure_client(client)
    abort "invalid client name \"#{client}\", must be one of: " +
      clients.join(', ') unless clients.include? client
    client
  end

  def jobs
    @jobs ||= bconsole.jobs
  end

  def restorable_jobs
    restorable_job_suffixes = jobs.select { |job|
      job.start_with? "#{restoreclient}:restore:"
    }.map { |job|
      job.slice(("#{restoreclient}:restore:".length)..-1)
    }

    jobs.select { |job|
      restorable_job_suffixes.any? { |suffix|
        job.end_with? ":backup:#{suffix}"
      }
    }
  end

  def ensure_restorable_job(backup_job)
    abort "invalid job name \"#{backup_job}\", must be one of: " +
      restorable_jobs.join(', ') unless restorable_jobs.include? backup_job
    backup_job
  end

  def restore_job_for(backup_job)
    backup_job.sub(/^[^:]+:backup:/, "#{restoreclient}:restore:")
  end

  def job_history
    bconsole.job_history
  end

  def successful_runs(backup_job)
    job_history.select { |record|
      record['Name'] == backup_job and
      record['Type'] == 'B' and # sanity check
      record['JobStatus'] == 'T'
    }
  end

  def last_successful_run(backup_job)
    successful_runs(backup_job).last
  end

  def restore(backup_job)
    restore_job = restore_job_for backup_job

    abort "can't restore \"#{backup_job}\" on \"#{restoreclient}\", " +
      "because the restore job \"#{restore_job}\" is missing" unless
      jobs.include? restore_job

    unless last_run = last_successful_run(backup_job)
      abort "no suitable jobid found for job \"#{backup_job}\""
    end

    puts "Restoring #{last_run['Job']} (JobId #{last_run['JobId']}) " +
      "on #{restoreclient}"

    cmdline = 'restore'
    cmdline << %{ jobid=#{last_run['JobId']}}
    cmdline << %{ fileset="#{last_run['FileSet']}"}
    cmdline << %{ client="#{last_run['ClientName']}"}
    cmdline << %{ restoreclient="#{restoreclient}"}
    cmdline << %{ select all done yes}
    output = bconsole.command cmdline

    if output =~ /^Select Restore Job \(\d+-\d+\): $\z/
      selection = nil
      output.scan(/^\s+(\d+): (.*)$/) do |number, job|
        if job == restore_job
          selection = number
          break
        end
      end
      if selection.nil?
        bconsole.command '.'
        raise "couldn't find restore job \"#{restore_job}\""
      end
      puts "Selected restore job #{restore_job}"
      output = bconsole.command selection
    else
      warn "Bacula might not have prompted for a restore job"
    end

    if output =~ /^Job queued. JobId=(\d+)$/
      jobid = $1
      puts "Waiting for Bacula job ##{jobid} to complete"
      status = bconsole.wait jobid
    else
      abort "unexpected output from Bacula: #{output}"
    end

    if status == 'T'
      puts "Bacula job ##{jobid} finished successfully"
    else
      abort "Bacula job ##{jobid} failed (status=#{status})"
    end
  end

  def run!
    case @action
    when :list_jobs
      abort "too many arguments" if ARGV.size > 0

      restorable_jobs.each do |job|
        if last_run = last_successful_run(job)
          last_run = last_run['Job']
        else
          last_run = "no previous successful run"
        end
        puts "#{job} (#{last_run})"
      end
    else
      if @all
        abort "can't specify jobs and --all" if ARGV.size > 0
        jobs = restorable_jobs
      elsif ARGV.size < 1
        abort "missing backup job name(s) or --all; try --list-jobs"
      else
        jobs = ARGV.each { |job| ensure_restorable_job(job) }
      end

      exitstatus = 0

      jobs.each do |job|
        begin
          restore job
        rescue RuntimeError => e
          if @force
            warn e.message
            exitstatus = 2
          else
            raise
          end
        end
      end

      exit exitstatus
    end
  end

  def self.run!
    program = self.new
    program.parse!
    program.run!
  end
end

if $0 == __FILE__
  BaculaRestore.run!
end
