# -*- mode: ruby -*-
# vi: set ft=ruby :

$:.unshift File.expand_path '../../../lib', __FILE__

require 'puppetize/vagrant/config'

# Test whether Vagrant and VeeWee can be installed successfully using
# the supplied top-level Rake task.  We cannot test whether they work,
# because nested virtual machines are not supported by VirtualBox.
Puppetize::Vagrant::Config.run "vagrant:install"
