# -*- mode: ruby -*-
# vi: set ft=ruby :

load "../Vagrantfile.inc"

Puppetize::Vagrant::Config::Quantal.run do |config|
  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  config.vm.forward_port 80, 8080

  # Apply ../../manifests/cloud.pp with Hiera data from ../../data.
  config.vm.provision :shell, :inline => \
    'cd /home/vagrant/infrastructure && rake puppetize:cloud'
end
