# -*- mode: ruby -*-
# vi: set ft=ruby :

$:.unshift File.expand_path '../../../lib', __FILE__

require 'puppetize/vagrant/config'

Puppetize::Vagrant::Config.run "puppetize:cloud" do |config|
  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  config.vm.forward_port 80, 8080
end
